apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
  namespace: {{ .Values.deployment.auth.namespace }}
data:
  init.sql: |
    -- Create tables for auth-service
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      username VARCHAR(255) UNIQUE NOT NULL,
      password_hash BYTEA NOT NULL
    );
    ALTER TABLE users OWNER TO {{ .Values.deployment.auth.postgres.username | quote }};

    -- Snake game scores table
    CREATE TABLE IF NOT EXISTS snake_high_scores (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      score INTEGER DEFAULT 0
    );
    ALTER TABLE snake_high_scores OWNER TO {{ .Values.deployment.auth.postgres.username | quote }};

    -- Other games stats
    CREATE TABLE IF NOT EXISTS games_stats (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      game_type VARCHAR(50) NOT NULL,
      wins INTEGER DEFAULT 0,
      losses INTEGER DEFAULT 0
    );
    ALTER TABLE games_stats OWNER TO {{ .Values.deployment.auth.postgres.username | quote }};

    -- Grant privileges dynamically
    GRANT ALL PRIVILEGES ON TABLE users TO {{ .Values.deployment.auth.postgres.username | quote }};
    GRANT ALL PRIVILEGES ON TABLE snake_high_scores TO {{ .Values.deployment.auth.postgres.username | quote }};
    GRANT ALL PRIVILEGES ON TABLE games_stats TO {{ .Values.deployment.auth.postgres.username | quote }};

    GRANT USAGE, SELECT, UPDATE ON SEQUENCE users_id_seq TO {{ .Values.deployment.auth.postgres.username | quote }};
    GRANT USAGE, SELECT, UPDATE ON SEQUENCE snake_high_scores_id_seq TO {{ .Values.deployment.auth.postgres.username | quote }};
    GRANT USAGE, SELECT, UPDATE ON SEQUENCE games_stats_id_seq TO {{ .Values.deployment.auth.postgres.username | quote }};

    GRANT CONNECT ON DATABASE {{ .Values.deployment.auth.postgres.db | quote }} TO {{ .Values.deployment.auth.postgres.username | quote }};
    GRANT USAGE ON SCHEMA public TO {{ .Values.deployment.auth.postgres.username | quote }};

    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {{ .Values.deployment.auth.postgres.username | quote }};
    GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO {{ .Values.deployment.auth.postgres.username | quote }};

    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {{ .Values.deployment.auth.postgres.username | quote }};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO {{ .Values.deployment.auth.postgres.username | quote }};
