apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.tlscert.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.tlscert.email }}
    privateKeySecretRef:
      name: {{ .Values.tlscert.name }}
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - kind: Gateway
                name: {{ .Values.gateway.name }}
                namespace: kgateway-system
