apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.auth.postgres.secretName }}
  namespace: {{ .Values.deployment.auth.namespace }}
type: Opaque
data:
  {{ .Values.deployment.auth.postgres.usernameKey }}: YWxwaGE=     # "alpha"
  {{ .Values.deployment.auth.postgres.passwordKey }}: Ymx1bnQ=     # "blunt”
